### PR TITLE
Algorithm for moving to specified pose

### PR DESCRIPTION
**Pull request by daniel-s-ingram**
There's some unstable behavior sometimes when the vehicle is at the same x or y position at the goal without actually being at the goal. I'll fix this, but it's hardcoded with values that work well right now.

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
@daniel-s-ingram Thank you every time. If you fix the unstable behavior, I will merge it.

**Comment by daniel-s-ingram** [comment]
@AtsushiSakai,

It's fixed now :) It was because my angles differences were in the range 0 to 2𝜋 instead of -𝜋 to +𝜋.

**Comment by AtsushiSakai** [comment]
@daniel-s-ingram Great! Thanks.

**Comment by AtsushiSakai** [comment]
@daniel-s-ingram By the way, I have the Peter Corke's book. Do you know which page the move_to_pose algorithm is written?

**Comment by daniel-s-ingram** [comment]
@AtsushiSakai,

It's on pages 106-109.

**Comment by AtsushiSakai** [comment]
@daniel-s-ingram Thanks!!

**Pull request merged**
