### PR TITLE
Fixed issue with float index for Python 2

### PR DESCRIPTION
**Pull request by daniel-s-ingram**
The floor function in Python 2 returns a float, leading to an index error in some cases. Converted indexes explicitly to ints.

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
@daniel-s-ingram Thank you so much for contributing again.
Let me ask one thing. 
Do you think the repository should work in Python2?
I don't want to do that... because the code becomes complicated.
The main purpose of this repo is for understating the algorithm's basic idea.

**Comment by daniel-s-ingram** [comment]
I think compatibility with Python 2 would be great to have for people who want to learn the algorithms but don't have Python 3 or its libraries installed due to potential conflicts with their own projects. If it's okay with you, I can keep fixing small issues like this without making the code any more complicated beyond the small changes I've been making.

**Comment by AtsushiSakai** [comment]
@daniel-s-ingram OK. I think this PR doesn't make the code so complicated. I will merge this PR. Thank you for your work again!!

**Comment by daniel-s-ingram** [comment]
Thank you - great repo, by the way!

**Pull request merged**
