### PR TITLE
More optimizations for DWA

### PR DESCRIPTION
**Pull request by goktug97**
Removed loops and vectorized all cost calculations

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
@goktug97 Hi, Thank you for you PR again. This repository "PythonRobotics" is for educational usage. So, Readability is more important than performance. So your PR is interesting but it seems difficult to understand the DWA algorithm. What do you think?

**Comment by goktug97** [comment]
I agree with you. I even thought adding the commit of the old version as a comment so that people can understand what is going on. I think this PR is really hard to understand.
Even my other PRs are kinda like that. Thank you merging them though :)

I like using python that is why I am trying to make it as fast as possible instead of accepting and using C++ :D 
I can create a new repo and link to this PR and repo.

**Comment by AtsushiSakai** [comment]
@goktug97 OK Thank you. I close this PR once. If you are ready, feel free to reopen it or create a new PR. By the way. I added your name in README as an author. I  appreciate your contribution : )

**Comment by goktug97** [comment]
> By the way. I added your name in README as an author. I appreciate your contribution : )

@AtsushiSakai Thank you. That means a lot. :)

**Pull request closed without merging**
