### PR TITLE
Forward Kinematics and Inverse Kinematics with 3D

### PR DESCRIPTION
**Pull request by takayuki5168**
I implemented **FK**(Forward Kinematics) and **IK**(Inverse Kinematics) with **3D** arm manipulator.

You can initialize manipulator with **Denavit-Hartenberg parameters**.

There are exapmles of FK and IK, random_*.py, initializing with Denavit-Hartenberg parameters of **PR2** robot.

Please advise me if you want this PR be merged.

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
@takayuki5168 Hi. First of all, thank you so much for your contribution. I like the 3D arm simulation.

**Comment by AtsushiSakai** [comment]
I have 2 requests.
- 1. Could you please add header comments for each script?
It like this: 
https://github.com/AtsushiSakai/PythonRobotics/blob/bb8b8b33d44d6ce3a04b2c16cd3a97fa36189abf/ArmNavigation/arm_obstacle_navigation/arm_obstacle_navigation.py#L1-L5

**Comment by AtsushiSakai** [comment]
2. Is it possible a script to make a animation? 
Ex) The 3D version of this animation
like: https://github.com/AtsushiSakai/PythonRobotics/blob/master/ArmNavigation/two_joint_arm_to_point_control/animation.gif

**Comment by AtsushiSakai** [comment]
Also, this is not mandatory for merging. 
Is it possible to make a technical documentation about this code?
It would be great like: [PythonRobotics/extended\_kalman\_filter\_localization\.ipynb at master · AtsushiSakai/PythonRobotics](https://github.com/)

**Comment by takayuki5168** [comment]
@AtsushiSakai Thanks for your replying.

Sure, I will work on that.

**Comment by AtsushiSakai** [comment]
@takayuki5168 Hi. I will close this PR once for task managing. If you are interested in adding animation for it. Please reopen it. Thanks

**Comment by AtsushiSakai** [comment]
@takayuki5168 Welcome  back!! Do you want to update the codes?

**Comment by takayuki5168** [comment]
@atsushi-sakai Sorry for absence. For now I won't update the main codes, but will write doc and code of ipynb.

**Comment by AtsushiSakai** [comment]
@takayuki5168 OK. Thank you!!

**Comment by AtsushiSakai** [comment]
I think we should merge your branch and close this PR. If your documents is ready to merge,  please create a new PR. Thank you for your contribution.

**Pull request merged**
