### PR TITLE
Greedy Best-First Search

### PR DESCRIPTION
**Pull request by guilyx**
Implement Greedy Best-First Search.

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
close and reopen to rerun CI.

**Comment by AtsushiSakai** [comment]
@guilyx I'm sorry for late review. Could you please pull upstream master to your branch and push it again? I updated CI setting in master branch.

**Comment by guilyx** [comment]
Done :+1:

**Comment by guilyx** [comment]
```
./PathPlanning/GreedyBestFirstSearch/greedy_best_first_search.py:88:80: E501 line too long (88 > 79 characters)
./PathPlanning/GreedyBestFirstSearch/greedy_best_first_search.py:103:1: W293 blank line contains whitespace
./PathPlanning/GreedyBestFirstSearch/greedy_best_first_search.py:108:80: E501 line too long (81 > 79 characters)
./PathPlanning/GreedyBestFirstSearch/greedy_best_first_search.py:118:1: W293 blank line contains whitespace
./PathPlanning/GreedyBestFirstSearch/greedy_best_first_search.py:127:9: E303 too many blank lines (2)
```
Fixing this.

**Comment by guilyx** [comment]
@AtsushiSakai Any idea what's wrong here ? I ran `rundiffstylecheck.sh` and it resulted in to style errors.

**Comment by AtsushiSakai** [comment]
@guilyx Sorry for that. Could you please pull upstream again and commit it again?

**Comment by guilyx** [comment]
It fails still, while succeeding locally @AtsushiSakai 😢

**Comment by AtsushiSakai** [comment]
@guilyx Thank you for your corporation. OK. let's ignore it. I will add a debug function for it. I don't know why this CI works correctly in my PR... Could you fix the CodeFactor issue? Maybe your new planning function is too complicated. It needs refactoring. Also I will start my review soon.

**Comment by guilyx** [comment]
The Code Factor issue comes from the Bidirectional A*. Not sure if I can tone it down but will try.

**Comment by guilyx** [comment]
@AtsushiSakai Not sure is Code Factor took into account the last commit, as it seems to have checked a tree last committed 16 hours ago

**Comment by AtsushiSakai** [comment]
Hmm. CodeFactor is weird, it does not updated.. and diffstylecheck works correctly... But anyway. I can merge it. Thank you for your contribution!!

**Pull request merged**
