### PR TITLE
Enhance lqr steering control docs

### LINKED ISSUE #992: What is the model used in lqr_steer_control.py?
Is there any documentation or related paper for this LQR lateral controller?
It seems like an error state model, but I don't know how to derive the linearized A,B matrix from scratch.
It would be great if there was some detailed explanation of the derivation steps.

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue

Fix #992 

#### CheckList
- [ ] Did you add an unittest for your new example or defect fix?
- [ ] Did you add documents for your new example?
- [ ] All CIs are green? (You can check it after submitting)

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
@lijieamd @Gopigunaganti @xiao-ge4 Is it possible to review this PR? You can check the updated doc here:

image

**Review by lijieamd — COMMENTED** [review]
Should the phi_t in the state vector be theta_t?

**Comment by lijieamd** [comment]
> @lijieamd @Gopigunaganti @xiao-ge4 Is it possible to review this PR? You can check the updated doc here:
> 
> image

@AtsushiSakai 
And could you please tell me how to check this CI generated html? It seems like it's an image rather than a link.

**Comment by AtsushiSakai** [comment]
Could you try to click the "Details" in the CI item.

**Pull request merged**
