### PR TITLE
Fix Hybrid A*

### PR DESCRIPTION
**Pull request by guilyx**
Fix issue #325

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
Thank you!! Is it possible to add a test? It is ok just adding a new test code in the tests dir.
a_star test code might help: https://github.com/AtsushiSakai/PythonRobotics/blob/master/tests/test_a_star.py

**Comment by guilyx** [comment]
@lentychang indeed !

**Comment by guilyx** [comment]
Added the tests and changed `N_STEER` according to @lentychang's suggestion.
@AtsushiSakai as `E722 do not use bare 'except` and all the tests uses bare excepts there might be something to do.

**Comment by AtsushiSakai** [comment]
@guilyx @lentychang Thank you guys!!. I will merge it. 

>  all the tests uses bare excepts there might be something to do.
Oh. Yes. these codes should do it. That's why I'm using incremental code check : ).

**Pull request merged**
