### PR TITLE
hybrid a star

### PR DESCRIPTION
**Pull request by zhengzh**
Hi, I translate your trailer_hybrid_a_star repo to python 2.7

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
This pull request **introduces 7 alerts** when merging a382689a30aeb822039c01609565c4260cb9e4b6 into 135e33af88128c68c0420282775bbfeacc327f77 - [view on LGTM.com](https://lgtm.com/projects/g/AtsushiSakai/PythonRobotics/rev/pr-b53c8a3efbf3930ca920896a895df7948b6dc330)

**new alerts:**

* 5 for Unused local variable
* 1 for Unused import
* 1 for Suspicious unused loop iteration variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AtsushiSakai** [comment]
@zhengzh Hi. Thank you for your great PR!! I have some requests.
1)
Python2.7 is not acceptable. Does this code work in Python 3.6 or higher?
2)
I think you should remove my name in each header and add your name on it. That is your code.

**Comment by AtsushiSakai** [comment]
@zhengzh Also, it would be great to fix some points according to PR #180 - AtsushiSakai/PythonRobotics - LGTM https://lgtm.com/projects/g/AtsushiSakai/PythonRobotics/rev/pr-b53c8a3efbf3930ca920896a895df7948b6dc330

**Comment by zhengzh** [comment]
@AtsushiSakai  Thanks for your response, I will fix it.

**Comment by AtsushiSakai** [comment]
This pull request **introduces 1 alert** when merging d8367b56b77dfb2008823468e56db1a5f151d445 into 135e33af88128c68c0420282775bbfeacc327f77 - [view on LGTM.com](https://lgtm.com/projects/g/AtsushiSakai/PythonRobotics/rev/pr-615eaa095276a103bff7c2d0dc4abb3646b949d6)

**new alerts:**

* 1 for Suspicious unused loop iteration variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AtsushiSakai** [comment]
@zhengzh Hi. Are you still interested in this issue? If not, I can fix it.

**Comment by zhengzh** [comment]
@AtsushiSakai Yes, thank you, please fix it.

**Comment by AtsushiSakai** [comment]
@zhengzh Oh I missed it. sorry. I will merge it. Thank you for your contribution!!

**Pull request merged**
