### PR TITLE
fix EKF

### PR DESCRIPTION
**Pull request by y011d4**
* In `efk_estimation`, the prediction step of `PPred` seems to be an typo (matrix multiplication of `np.array` should be described by not `*` but `np.dot`).
* If I understand correctly, the calculation of `xPred` should not contain noise. So not `ud` but `u` should be used.
* In `observation`, noise in control is described as `Rsim` and one in observation is as `Qsim`, while in `efk_estimation`  `Q` and `R`. I think those notations should be unified (I adopted the same notation as the book, *Probabilistic Robotics*).

The comments below, about which I fixed nothing at all, contains my questions about the simulation implemented in EKF algorithm. I have no confidence because I'm just a beginner for this field.

* Aren't roles `xTrue` and `xDR` opposite? The true trajectory is determined by the control including noise.
* Accordingly the position observation should be changed so that it detects the `xDR` plus noise.

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
@y011d4 Hi. Thank you for your PR.

**Comment by AtsushiSakai** [comment]
I agree
> In efk_estimation, the prediction step of PPred seems to be an typo (matrix multiplication of np.array should be described by not * but np.dot).

and 
> In observation, noise in control is described as Rsim and one in observation is as Qsim, while in efk_estimation Q and R. I think those notations should be unified (I adopted the same notation as the book, Probabilistic Robotics).

However, I don't agree this:
>If I understand correctly, the calculation of xPred should not contain noise. So not ud but u should be used.
Because, the EKF estimation can only use ud (input with noise) because all sensor has noise.

**Comment by y011d4** [comment]
> However, I don't agree this:

  >> If I understand correctly, the calculation of xPred should not contain noise. So not ud but u should be used.

> Because, the EKF estimation can only use ud (input with noise) because all sensor has noise.
> What do you think?

I thought that `u` is the control value we want to apply and `ud` is the exact control value the GOD only knows, so we cannot obtain `ud`.
But it seems that the value `ud` can be obtained somehow. I took a mistake about considered situations.
Thank you for your kindful comments!

I fixed some as you pointed out.

**Comment by AtsushiSakai** [comment]
@y011d4 > But the situation is that ud is observation noise of u like wheel odometry.
Yes, that is what I mean. Thank you so mush for fixing the bug and cleaning up it!!
I will merge it.

**Pull request merged**
