### PR TITLE
fix ellisoid calculation

### PR DESCRIPTION
**Pull request by yuokamoto**
Hello, I'm studying robotics with your repository and I found small bug in code.

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
@karanchawla Is it possible for you to review this PR?

**Comment by karanchawla** [comment]
Sure will look at it today evening.

**Comment by AtsushiSakai** [comment]
@karanchawla Is it ok for merging?

**Comment by karanchawla** [comment]
@atsushi-sakai yes this is correct.

**Comment by AtsushiSakai** [comment]
@karanchawla Thank you for reviewing!!

**Pull request merged**
