### PR TITLE
Lidar measurement to grid map

### PR DESCRIPTION
**Pull request by horverno**
This example shows how to convert a 2D range measurement to a grid map. This is the basis of creating occupancy grid map eg for SLAM.

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
This pull request **introduces 3 alerts** when merging affcc3f1fded2e26c325f3ad3fd198e40d2cf26f into 9d1a05a5810d61f689cffaf4afdb5143de130cdb - [view on LGTM.com](https://lgtm.com/projects/g/AtsushiSakai/PythonRobotics/rev/pr-7a3dc6a8ce4593fdb7dbac3dfa75e7d774b09d73)

**new alerts:**

* 2 for Unused local variable
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AtsushiSakai** [comment]
This pull request **introduces 1 alert** when merging 5d6927a7d9be841a759b6f5aa8a6d64ae535b552 into 9d1a05a5810d61f689cffaf4afdb5143de130cdb - [view on LGTM.com](https://lgtm.com/projects/g/AtsushiSakai/PythonRobotics/rev/pr-03d4311c30b33543d2b499b54b7b17e26a5cacfd)

**new alerts:**

* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AtsushiSakai** [comment]
@horverno Thank you so much for your PR. It is interesting. However, opencv dependency is not acceptable for me. Could you remove it?

**Comment by horverno** [comment]
@AtsushiSakai, thanks, will check out if i can get rid of opencv

**Comment by kyberszittya** [comment]
Only FloodFill was used from OpenCV, I've get rid of it.

**Comment by AtsushiSakai** [comment]
@horverno @kyberszittya Thank you so much for you guys contribution!!.

**Pull request merged**
