### PR TITLE
Update extended_kalman_filter.py

### PR DESCRIPTION
**Pull request by minxuanjun**
Jacoby's formula is wrong

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
@minxuanjun Thank you for your contribution.
Could you please explain why the element should be 0?
I think v_{t+1} = v{t}, so dv(t)/dv = 1.0.

**Comment by minxuanjun** [comment]
@AtsushiSakai , because your matrix F[3,3]==0

**Comment by minxuanjun** [comment]
@AtsushiSakai  I think x and u are different state variable , d(f(x,u))/dx  and d(f(x,u))/dx should be separated.

**Comment by AtsushiSakai** [comment]
@minxuanjun  Based on wikipedia article, the state equation f(x,u) seems to include both matrixs. Extended Kalman filter - Wikipedia https://en.wikipedia.org/wiki/Extended_Kalman_filter 
And the jacobian is differentiated by both current x and u.
Do you have any reference about your idea?

**Comment by minxuanjun** [comment]
@AtsushiSakai  I reference the chapter7 of Probabilistic robot。

**Comment by AtsushiSakai** [comment]
@minxuanjun I think the difference came from noise modeling. In my case, I assume that gaussian noise is added to state, not input for simplicity. In the Probabilistic Robotics, they assume noise is added to input.

**Comment by minxuanjun** [comment]
@AtsushiSakai thank you.

**Comment by AtsushiSakai** [comment]
@minxuanjun Thank you so much too for taking your time. I appreciate good disquisition with you.

**Pull request closed without merging**
