### PR TITLE
DWA cost function toward goal

### PR DESCRIPTION
**Pull request by KoenHan**
Signed-off-by: KoenHan <sliver1998324@gmail.com>

I changed it as follows:
- Changed the computation method of to_goal_cost.
   Implemented calc_to_goal_cost function more closely to the method proposed in the paper of DWA.

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
@KoenHan Thank you for your PR. I changed the title of the PR.

**Comment by AtsushiSakai** [comment]
@KoenHan This function wrote by another guy in #126 . In the first version of it, I used a distance function for the goal cost. But he changed it to using angle towards the goal for the cost.

**Comment by AtsushiSakai** [comment]
@KoenHan It seems that you are right. His implementation is just calculating the angle between robot position vector and goal vector from the origin. I will merge it. Thank you for your great PR!!

**Comment by AtsushiSakai** [comment]
@KoenHan I cleaned up the code and refactoring. Please check the latest master code.

**Comment by KoenHan** [comment]
I understand.
Thank you, too!

**Pull request merged**
