### PR TITLE
Add requirements file

### PR DESCRIPTION
**Pull request by FavioVazquez**
Obtained from running `pipreqs`

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
@FavioVazquez Thank you for your interesting PR. Do you know why does it includes tweepy, tqdm, ascii_graph? I don't use it.

**Comment by AtsushiSakai** [comment]
@FavioVazquez Also, I don't want to fix the versions. I want to try use the latest ones.

**Comment by FavioVazquez** [comment]
It's weird. I used pipreqs, that should get what packages are being used here correctly. Let me update that!

**Comment by AtsushiSakai** [comment]
@FavioVazquez Thank you for updating.

**Pull request merged**
