### PR TITLE
Bidirectional Breadth-First Search

### PR DESCRIPTION
**Pull request by guilyx**
Implement Bidirectional Breadth-First Search algorithm.

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
close and reopen to rerun CI.

**Comment by guilyx** [comment]
```
./PathPlanning/BidirectionalBreadthFirstSearch/bidirectional_breadth_first_search.py:99:80: E501 line too long (88 > 79 characters)
./PathPlanning/BidirectionalBreadthFirstSearch/bidirectional_breadth_first_search.py:139:80: E501 line too long (98 > 79 characters)
./PathPlanning/BidirectionalBreadthFirstSearch/bidirectional_breadth_first_search.py:143:80: E501 line too long (98 > 79 characters)
./PathPlanning/BidirectionalBreadthFirstSearch/bidirectional_breadth_first_search.py:151:80: E501 line too long (84 > 79 characters)
Error: Your changes contain pycodestyle errors.
```

Fixing this.

**Comment by AtsushiSakai** [comment]
Thanks @guilyx !!

**Comment by AtsushiSakai** [comment]
@guilyx Also, I added you as an author of this repo. Please check README. Thanks!!

**Pull request merged**
