### PR TITLE
fix appveyor

### PR DESCRIPTION
**Pull request by jwdinius**

### CODE REVIEW

**Comment by jwdinius** [comment]
I was able to use the conda environment definition from the repo's `environment.yml` file to install all dependencies within that conda environment.  This fixes the broken appveyor ci.  All CI checks pass now.

**Comment by AtsushiSakai** [comment]
@jwdinius Hi. Thank you for your PR. I’m sorry my laptop is broken now, I will check it later.

**Comment by AtsushiSakai** [comment]
@jwdinius Great!!.

**Comment by AtsushiSakai** [comment]
fix #153

**Pull request merged**
