### PR TITLE
HTML Docs

### PR DESCRIPTION
**Pull request by araffin**
Hello,
This PR (see #99 ) move most of the README content into proper documentation files.

For now, I have set it up with my fork here: https://pythonrobotics.readthedocs.io
You will need to configure read the docs (http://readthedocs.org/) once this PR is merged (btw, tell me when I should delete mine so you can use the "pythonrobotics" domain name on read the docs ;) ).

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
@araffin Thank you for your great PR!! It is very beautiful doc. I love it. I'm ready to create the page on readthedocs. Please let me know when you delete your page. Thanks again!!.

**Comment by AtsushiSakai** [comment]
@araffin However, I want to left some animations in README.md, because many people just watch the README at first time. so I will put back some animations to the README.md later.

**Comment by AtsushiSakai** [comment]
@araffin the build is crash...
> Don't forget to check 'use system packages' in advanced settings, 
ss 2018-09-16 21 06 28

This check box? Do you know there are any other setting which I have to do?

**Comment by AtsushiSakai** [comment]
@araffin The build message is this

ss 2018-09-16 21 11 04

**Comment by araffin** [comment]
Yes, that is this checkbox. I would also recommend switching to Cpython 3x interpreter.
Did you check anything else ? (It's weird, it looks like its trying to install it as a package, it did not append on my side)

**Comment by araffin** [comment]
@AtsushiSakai it looks like this checkbox (see below) was checked (it should not):
rtd

**Comment by AtsushiSakai** [comment]
@araffin Oh, it works!!. Thank you.

**Pull request merged**
